# Generated by Django 3.1.4 on 2021-08-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('skill', models.CharField(default='', max_length=200)),
                ('twitter', models.CharField(default='', max_length=200)),
                ('facebook', models.CharField(default='', max_length=200)),
                ('instagram', models.CharField(default='', max_length=200)),
                ('linkedin', models.CharField(default='', max_length=200)),
                ('github', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
