# Generated by Django 3.1.4 on 2021-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Classname', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.CharField(default='', max_length=200)),
                ('Age', models.CharField(default='', max_length=200)),
                ('Website', models.CharField(default='', max_length=200)),
                ('Education', models.CharField(default='', max_length=200)),
                ('Phone', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
                ('City', models.CharField(default='', max_length=200)),
                ('Freelance', models.CharField(default='', max_length=200)),
                ('HappyClient', models.CharField(default='', max_length=200)),
                ('Project', models.CharField(default='', max_length=200)),
                ('GithubRepo', models.CharField(default='', max_length=200)),
                ('Certificates', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Percent', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='facebook',
            new_name='Facebook',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='github',
            new_name='Github',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='instagram',
            new_name='Instagram',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='linkedin',
            new_name='Linkedin',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='skill',
            new_name='Overview',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='twitter',
            new_name='Twitter',
        ),
    ]
