# Generated by Django 3.1.4 on 2021-08-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210825_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='sid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
