# Generated by Django 3.1.4 on 2021-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_skill_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(default='', upload_to='media')),
                ('Description', models.CharField(default='', max_length=200)),
                ('Title', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
