# Generated by Django 3.1.4 on 2021-08-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
