# Generated by Django 3.1.4 on 2021-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_home_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Project_Name', models.CharField(default='', max_length=200)),
                ('Tools', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Year', models.CharField(default='', max_length=200)),
                ('College', models.CharField(default='', max_length=200)),
                ('Board', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Gender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Hobbies',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Language',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Nationality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
