# Generated by Django 3.1.4 on 2021-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210825_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(default='', upload_to='media')),
                ('Gif2', models.ImageField(default='', upload_to='media')),
                ('Gif3', models.ImageField(default='', upload_to='media')),
                ('Gif4', models.ImageField(default='', upload_to='media')),
                ('Project_Date', models.CharField(default='', max_length=200)),
                ('Project_Url', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
