# Generated by Django 3.1.4 on 2021-08-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_information',
            name='Image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
