# Generated by Django 3.1.4 on 2021-09-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
